language: node_js
# node_js:
# -  "16.13.2"

# install:
# - npm install newman

# before_script:
# - node --version
# - npm --version
# - node_modules/.bin/newman --version
# script:
#   - node_modules/.bin/newman run tests/Order-New-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json
#   - node_modules/.bin/newman run tests/Order-Existing-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json

jobs:
  include:
    - name: 'Automated API tests using Postman CLI'
      arch: amd64
      os: linux
      dist: focal
      node_js:
        - 17
      script:
        # Install Postman CLI
        - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        # Login using your Postman API Key
        - postman login --with-api-key $POSTMAN_API_KEY
        # Run your collections using Postman CLI
        - postman collection run "${HOME}/postman/collections/Order New User.json"
        # Lint your API using Postman CLI
        - postman api lint b6665f8d-f35b-4eef-a246-7c66cbff358a