language: node_js
node_js:
  - 18.0

services:
  - docker

# safelist
branches:
  only:
  - master

before_script:
  - docker-compose up -d
  - docker-compose ps

script:
  - docker-compose exec postman run tests/Order-New-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json -r cli,junit --reporter-junit-export tests/report.xml
  - docker-compose exec postman run tests/Order-Existing-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json -r cli,junit --reporter-junit-export tests/report.xml

after_script:
  - docker-compose down