version: "3"

services:
  payload:
    image: node:16-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev && yarn add newman && yarn add newman-reporter-json && newman  run tests/User-auth.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json  -r cli,json"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - app-network

  postman:
    image: postman/newman:alpine
    container_name: postmanTests
    environment:
      PAYLOAD_HOST: payload
    command:
      # run tests/Order-New-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json  -r cli,json
      # --reporter-json-export="reports/report.json"
      run tests/User-auth.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json  -r cli,json
      --reporter-json-export="reports/report.json"
    volumes:
      - .:/etc/newman
    depends_on:
      - payload
    networks:
      - app-network

      # | run tests/Order-Existing-User.postman_collection.json -e tests/LMS-ENV-LOCAL.postman_environment.json

networks:
  app-network:
    driver: bridge

volumes:
  data:
  node_modules: