version: '3'

services:
  mongo-sync:
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-sync-data:/data/db
volumes:
  mongo-sync-data: {}